name: casper-validators
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("renv")' 
          R -e 'renv::restore()'
          
      - name: Analyze some penguin beaks
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          R -e 'renv::run("main.R")'
          # Add picture
          cml-publish RAM Amount Chart.png --md > report.md 
          # Add picture
          cml-publish Step Time Chart.png --md > report.md 
          # Send report
          cml-send-comment report.md